spring.application.name=pedido
server.port = 8081
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/ms-pedido
spring.datasource.username=postgres
spring.datasource.password=26119226
spring.jpa.hibernate.ddl-auto=update


